# Generated by Django 5.2.6 on 2025-09-16 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='nome_completo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
