# Generated by Django 5.2.6 on 2025-09-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('aberto', 'Em aberto'), ('finalizado', 'Finalizado'), ('pago', 'Pago'), ('enviado', 'Enviado')], default='aberto', max_length=20),
        ),
    ]
